### ISSUE TITLE
Is this support wechat and weibo？

### ISSUE THREAD

**Issue by cynhard** [overtrue/laravel-socialite#1]
Is this support wechat and weibo？I have no idea about this，and reported "Call to undefined method Overtrue\LaravelSocialite\Socialite::driver()",can you help me？

**Comment by overtrue** [comment]
@cynhard https://github.com/overtrue/socialite 支持微博，微信公众号，微信网页登录

报错的问题，请你贴一下你的用法，步骤。

**Comment by cynhard** [comment]
@overtrue 刚开始用的是`use Overtrue\LaravelSocialite\Socialite;`，用`use Socialite;`就不报这个错误了，谢谢
