### ISSUE TITLE
Laravel5.5安装有问题

### ISSUE THREAD

**Issue by LaravelChen** [overtrue/laravel-socialite#12]
我发现你你的composer里面添加了laravel5.5增加的extra这个字段，自动注入porvider和alias，那么我安装完之后，发现vendor目录中的laravel-soclite文件是空的，请解决一下!

**Comment by wanghanwanghan** [comment]
这个问题解决了吗

**Comment by overtrue** [comment]
@wanghanwanghan 请描述问题现象，目录无法重现上面描述的问题

**Comment by wanghanwanghan** [comment]
> @wanghanwanghan 请描述问题现象，目录无法重现上面描述的问题

没事了超哥，我这边没发现有问题，可以正常用的~
