### ISSUE TITLE
感谢大佬

### ISSUE THREAD

**Issue by nekoimi** [overtrue/laravel-socialite#15]
我操了你的代码，公司使用的Lumen，不太想搞session支持，第三方登录的state改成外部传递了，借助redis可以保存更多的零时数据。感谢大佬开源

**Comment by nekoimi** [comment]
打错w(ﾟДﾟ)w

**Comment by overtrue** [comment]
心疼我的代码……

Nekoimi <notifications@github.com>于2019年11月25日 周一下午11:43写道：
