### ISSUE TITLE
不能同时支持微信公众号和开放平台吗？service.php只有一个wechat配置

### ISSUE THREAD

**Issue by aoxiaoxi** [overtrue/laravel-socialite#17]
不能同时支持微信公众号和开放平台吗？service.php只有一个wechat配置，pc端做开放平台，手机端做公众号，该怎么配置一下呢？

**Comment by overtrue** [comment]
3.0 将会支持

**Comment by aoxiaoxi** [comment]
感谢回复，我这边实现了。
login入口判断了来自公众号还是开放平台。然后生成统一的wechat配置文件。没用larave的门面，直接new SocialiteManager()，然后-&gt;driver ('wechat')就可以了。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 安正超 <notifications@github.com&gt;
发送时间: 2020年7月17日 11:57
收件人: overtrue/laravel-socialite <laravel-socialite@noreply.github.com&gt;
抄送: aoxiaoxi <823820360@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[overtrue/laravel-socialite] 不能同时支持微信公众号和开放平台吗？service.php只有一个wechat配置 (#17)





 
3.0 将会支持

**Comment by overtrue** [comment]
嗯
