### ISSUE TITLE
laravel8咋报这错

### ISSUE THREAD

**Issue by nfhh** [overtrue/laravel-socialite#20]
![image](https://user-images.githubusercontent.com/30310521/98200029-a24d4e80-1f67-11eb-8304-e9da97bf17a7.png)

**Comment by overtrue** [comment]
请确认你安装的版本，socialite 3 和 2 的语法不一样哦。

**Comment by nfhh** [comment]
> 请确认你安装的版本，socialite 3 和 2 的语法不一样哦。

![image](https://user-images.githubusercontent.com/30310521/98200938-9f535d80-1f69-11eb-8cf3-edfea5567bc6.png)

![image](https://user-images.githubusercontent.com/30310521/98201020-c742c100-1f69-11eb-92c1-112a24e0b32f.png)

**Comment by overtrue** [comment]
https://github.com/overtrue/laravel-socialite/blob/master/README.md#usage 文档忘记改，已更新

**Comment by nfhh** [comment]
> https://github.com/overtrue/laravel-socialite/blob/master/README.md#usage 文档忘记改，已更新

👍

**Comment by nfhh** [comment]
stateless方法还有吗？
$user = Socialite::create('github')->stateless()->userFromCode($request->query('code')); 这样？

**Comment by overtrue** [comment]
没有

**Comment by nfhh** [comment]
> 没有

没有替代方法吗？为啥废弃啊 感觉这方法有用

**Comment by overtrue** [comment]
@nfhh https://github.com/overtrue/socialite#state

**Comment by nfhh** [comment]
> @nfhh https://github.com/overtrue/socialite#state
![image](https://user-images.githubusercontent.com/30310521/98202354-cbbca900-1f6c-11eb-89f7-fa2331a6c0aa.png)
![image](https://user-images.githubusercontent.com/30310521/98202383-daa35b80-1f6c-11eb-94f9-99b28c186659.png)
回调回来有问题

**Comment by nfhh** [comment]
> > @nfhh https://github.com/overtrue/socialite#state
> > ![image](https://user-images.githubusercontent.com/30310521/98202354-cbbca900-1f6c-11eb-89f7-fa2331a6c0aa.png)
> > ![image](https://user-images.githubusercontent.com/30310521/98202383-daa35b80-1f6c-11eb-94f9-99b28c186659.png)
> > 回调回来有问题

难道你这个最新版不支持QQ微信微博？

**Comment by overtrue** [comment]
麻烦看清楚报错，`driver` 不存在，是 `create`
