### ISSUE TITLE
config/socialite.php 这个文件是需要自建建立么？

### ISSUE THREAD

**Issue by OranTing** [overtrue/laravel-socialite#3]
如题。谢谢。

**Comment by overtrue** [comment]
Laravel 不需要自己写，有命令生成，我文档上也写了。

Sent using CloudMagic Email [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=7.11.24&pv=9.3.1&source=email_footer_2]
On 周二, 6月 21, 2016 at 11:58 上午, Ruihua notifications@github.com wrote:
如题。谢谢。

**Comment by OranTing** [comment]
是这个么？php artisan vendor:publish   我运行了并没有生成呀。看了文档上也没有看到相关说明。麻烦了。

**Comment by ghost** [comment]
@OranTing 先清理缓存
`php artisan config:cache`
