### ISSUE TITLE
使用Google登录，可以redirect，但获取超时

### ISSUE THREAD

**Issue by liuyami** [overtrue/laravel-socialite#4]
目前只测试了用 Google 登录，测试地址是：https://demo.365sy.com/oauth/google 返回超时。如果是服务器之间的通信问题，不应该有返回参数，如：https://demo.365sy.com/oauth/google/callback?state=7b9129f11eacc911264eef0ea313592e0c77235d&code=4/5LZy-2yHwmXlkbopoWO3L4OQDSSeIZ7-tPMVhXHvusI&authuser=0&session_state=af1163bacd1e5ea237d2c6f4ef851591aca6bc8c..30d0&prompt=none#

代码完全按照DEMO写的，只不过把github改成google

**Comment by overtrue** [comment]
请在你的服务器上 curl 请求一下 Google 的 oauth 地址，保证你的服务器能访问 Google.

Sent using CloudMagic Email [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=7.11.24&pv=9.3.1&source=email_footer_2]
On 周五, 6月 24, 2016 at 8:28 上午, liuyami notifications@github.com wrote:
目前只测试了用 Google 登录，测试地址是： https://demo.365sy.com/oauth/google [https://demo.365sy.com/oauth/google] 返回超时。如果是服务器之间的通信问题，不应该有返回参数，如： https://demo.365sy.com/oauth/google/callback?state=7b9129f11eacc911264eef0ea313592e0c77235d&code=4/5LZy-2yHwmXlkbopoWO3L4OQDSSeIZ7-tPMVhXHvusI&authuser=0&session_state=af1163bacd1e5ea237d2c6f4ef851591aca6bc8c..30d0&prompt=none# [https://demo.365sy.com/oauth/google/callback?state=7b9129f11eacc911264eef0ea313592e0c77235d&code=4/5LZy-2yHwmXlkbopoWO3L4OQDSSeIZ7-tPMVhXHvusI&authuser=0&session_state=af1163bacd1e5ea237d2c6f4ef851591aca6bc8c..30d0&prompt=none]

代码完全按照DEMO写的，只不过把github改成google

**Comment by liuyami** [comment]
感谢，的确是服务器无法连接到google，忘记本地是用了工具而忽略了服务器
