### ISSUE TITLE
laravel5.4 session set应该改为put

### ISSUE THREAD

**Issue by moore0903** [overtrue/laravel-socialite#5]
安神,你好,laravel5.4中,session的set()方法应该更换成put()

引用5.4中的升级说明
Symfony兼容性#

Laravel 的会话处理程序不再实现 Symfony 的 SessionInterface 。 实现这个接口需要我们实现框架不需要的无关特性。取而代之，已经定义了新的 Illuminate\Contracts\Session\Session 接口，并且可以使用。还应该修改一下代码：

所有调用 ->set() 方法应该更改为 ->put() 。通常，Laravel 应用从不调用 set 方法，因为它从未在 Laravel 文档中记录。不过，谨慎起见，这里我们依然罗列出来。

所有调用 ->getToken() 方法的地方需要修改为 ->token() 。

所有调用 $request->setSession() 方法的地方需要求改为 setLaravelSession() 。

**Comment by overtrue** [comment]
> https://github.com/overtrue/socialite/blob/master/src/Providers/AbstractProvider.php#L168

**Comment by overtrue** [comment]
> 所有调用 ->getToken() 方法的地方需要修改为 ->token() 。
> 所有调用 $request->setSession() 方法的地方需要求改为 setLaravelSession() 。

这是在说哪里？

**Comment by moore0903** [comment]
哦哦,我没看git上的代码,应该用dev的,这两个我也没看到,只是从升级说明复制的一大段

**Comment by overtrue** [comment]
@moore0903 哦
