### ISSUE TITLE
Type error: Argument 1 passed to Overtrue\Socialite\SocialiteManager::formatConfig() must be of the type array, null given, called in /.../vendor/overtrue/socialite/src/SocialiteManager.php on line 149

### ISSUE THREAD

**Issue by rbenvenuto** [overtrue/laravel-socialite#9]
I know there is another Issue opened with this same error, but i still can't solve it.

After the user authorizes my App into his/her Facebook, is redirected to this error.

`Type error: Argument 1 passed to Overtrue\Socialite\SocialiteManager::formatConfig() must be of the type array, null given, called in /.../vendor/overtrue/socialite/src/SocialiteManager.php on line 149`

I noticed the `overtrue/laravel-socialite/config.php` file is empty.

Is there some configuration file missing?

I already tried:
`php artisan vendor:publish`
`php artisan config:cache`

But none worked, what should i do?

Laravel Framework 5.4.32

**Comment by gozhhu** [comment]
how to solve it? thx @rbenvenuto
